name: BuildTestDeploy
on:
    push:
        branches:
            - "*" # matches every branch that doesn't contain a '/'
            - "*/*" # matches every branch containing a single '/'
            - "**" # matches every branch
jobs:
    BuildTestDeploy:
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Locking the build queue
              run: workflow_queue queue lfx

            - name: Use Node 16
              shell: bash --login {0}
              run: |
                echo {0}
                nvm use 16

            - name: Installing Packages
              run: |
                npm install

            - name: Building the Project
              run: |
                npm run build

            # - name: Development Deployment
            #   if: ${{ github.ref == 'refs/heads/develop' }}
            #   run: |
            #     ssh virtuo@lfstation "mkdir -p ~/castingapp && cd ~/castingapp && ./build-app-image.sh castingapp dev && ./swap-all.sh castingapp dev"

            # - name: Production Deployment
            #   if: ${{ github.ref == 'refs/heads/master' }}
            #   run: |
            #     ssh virtuo@167.71.69.147 "mkdir -p ~/castingapp && cd ~/castingapp && ./build-app-image.sh castingapp prod && ./swap-all.sh castingapp prod"

            - name: Use Node LTS
              shell: bash -l {0}
              run: nvm use --lts

            - name: Unlocking The Build Queue
              if: always()
              run: workflow_queue clear lfx
